### ISSUE TITLE
AttributeError: '_ErrorHolder' object has no attribute '_testMethodDoc'

### ISSUE THREAD

**Issue by Hidderr** [GoverSky/HTMLTestRunner_cn#8]
Traceback (most recent call last):
  File "D:/machine_Learning/machine_pycharm/untitled/CommonSdk/ScreenShot/Report.py", line 177, in <module>
    runer.run(suiteAll)
  File "D:\machine_Learning\Lib\HTMLTestRunner_cn.py", line 888, in run
    self.generateReport(test, result)
  File "D:\machine_Learning\Lib\HTMLTestRunner_cn.py", line 941, in generateReport
    report = self._generate_report(result)
  File "D:\machine_Learning\Lib\HTMLTestRunner_cn.py", line 1011, in _generate_report
    self._generate_report_test(rows, cid, tid, n, t, o, e)
  File "D:\machine_Learning\Lib\HTMLTestRunner_cn.py", line 1028, in _generate_report_test
    doc = t._testMethodDoc or ''
AttributeError: '_ErrorHolder' object has no attribute '_testMethodDoc'

请问，我故意给要测试的app添加的异常，然后就Pycharm控制台就输出这个bug,我不添加异常则能正常生成报告的HTML，添加了则不行请问是什么原因呢？

**Comment by GoverSky** [comment]
能描述一下怎么添加的异常么

**Comment by GoverSky** [comment]
能描述一下怎么添加的异常么

**Comment by Hidderr** [comment]
就是给App添加了一行代码：int b = 3/0; 即除0的异常，我发现只要appium未连接，也会报这个异常，请问，AttributeError: '_ErrorHolder' object has no attribute '_testMethodDoc'，请问还有什么情况下会报这个异常，

**Comment by HinsTing** [comment]
请问这个driver的初始化失败你是怎么解决的？我也遇到了这个报错的情况
